### ISSUE TITLE
Wait State does not support Timestamp and TimestampPath. 

### ISSUE THREAD

**Issue by philippdonabauer** [flocasts/serverless-offline-step-functions#4]
Wait state does not support following:

Timestamp and TimestampPath.

Please add this functionality.
Please also update your Readme document. 

Thank you for this serverless offline plugin, keep going.

**Comment by jkruse14** [comment]
This will be supported with PR #6

**Comment by jkruse14** [comment]
@philippdonabauer should be good to go!

**Comment by philippdonabauer** [comment]
Thank you very much!

Now i can test locally!
