### ISSUE TITLE
You should add an License

### ISSUE THREAD

**Issue by philippdonabauer** [flocasts/serverless-offline-step-functions#9]
Please add an license.

Serververless offline is under MIT [License](https://github.com/dherault/serverless-offline/blob/master/LICENSE).

It would be good when your Project is also under the MIT.

And thank you again for your greate work ;)

**Comment by jkruse14** [comment]
Not sure how I missed that... Thanks for the heads up! I'll get that added!

**Comment by jkruse14** [comment]
@philippdonabauer - There is a License in GitHub (MIT)

**Comment by philippdonabauer** [comment]
Thank you very much!
